---
sudo: required

services:
  - docker

language: go
go:
  - "1.15"
  - master

matrix:
  allow_failures:
  - go: master

script:
  - go test . ./recras ./odata2json ./synctool
  - test "${TRAVIS_GO_VERSION}" = "1.15" && docker build . || true
