---
sudo: required

services:
  - docker

language: go
go:
  - 1.5
  - 1.6
  - tip

install: []

script:
  - [ "${TRAVIS_GO_VERSION}" = "1.5" ] && export GO15VENDOREXPERIMENT="1"
  - go test . ./recras ./odata2json ./synctool
  - [ "${TRAVIS_GO_VERSION}" = "tip" ] && docker build .
