---
sudo: required

services:
  - docker

language: go
go:
  - 1.5
  - 1.6
  - tip

install:
  - test "${TRAVIS_GO_VERSION}" = "1.5" && export GO15VENDOREXPERIMENT="1" || true

script:
  - go test . ./recras ./odata2json ./synctool
  - test "${TRAVIS_GO_VERSION}" = "tip" && docker build . || true
