---
exactonline:
  build: ./
  ports:
    - "80:8888"
  links:
    - postgres
  environment:
    EXACT_CLIENT_SECRET:
    EXACT_CLIENT_ID:
    EXACT_REDIRECT_URL:

postgres:
  image: postgres:9.5
  environment:
    POSTGRES_USER: exactonline
    POSTGRES_PASSWORD: asdfasdfasdf
