#!/usr/bin/env bash

echo "Creating database exactonline..."
createdb exactonline

echo "Running migration on postgres://nederdirk@localhost:5432/exactonline?sslmode=disable..."
migrate -url postgres://nederdirk@localhost:5432/exactonline?sslmode=disable -path ./migrations up

echo "Creating database exactonline-test"
createdb exactonline-test

echo "Running migration on postgres://nederdirk@localhost:5432/exactonline-test?sslmode=disable..."
migrate -url postgres://nederdirk@localhost:5432/exactonline-test?sslmode=disable -path ./migrations up